version: '3.7'

services:
  application:
    build: .
    container_name: application
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TYPEORM_HOST=host.docker.internal
      - CAMDIGKEY_URL=http://auth-camdigkey:3020
      - API_PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "dist/main"]

  db:
    container_name: db
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PG_DATA=/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${TYPEORM_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  auth-camdigkey:
    image: docker.dev.digitaleconomy.gov.kh/camdigikey-auth:release-1.0.0
    container_name: auth-camdigkey
    ports:
      - "3001:3020"
    env_file:
      - .env.camdigkey
    volumes:
      - ./keystore:/usr/src/app/build/src/keystore
      
  fileStorage:
    image: minio/minio
    container_name: fileStorage
    ports:
      - "9000:9000" # Change the left side to specify a different host port if needed
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root12345
    volumes:
      - ./min-data:/data # Map a local directory to store MinIO data
    command: server /data --console-address ":9090"
volumes:
  pgdata: